### PR TITLE
Takes care of condition when no parameters are passed with keep

### PR DESCRIPTION
**Pull request by zorroblue**
This will take care of the exception faced when just 'keep' is passed.
Simple fix,I guess.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Awesome. Small suggestion : We should make something like [this](https://github.com/OrkoHunter/ping-me/blob/master/ping_me/ping.py#L238-L242). A separate function with better printing. That should be good.

**Comment by zorroblue** [comment]
Yup! That's better!

**Comment by zorroblue** [comment]
Something like this? 
def print_error_message():
    print("Usages :\n1. keep [options]\nOptions: show | list "+"\n2. keep <command_name>\n followed by brief description on the next line")   

If it is OK, I will send a new PR :)

**Comment by OrkoHunter** [comment]
Yup, this one seems to be great.
```py
print("Usages :")
print("\n1. keep <code>")
print("<description of code>")
print("\n2. keep [options]")
print("Options: show | list ")
```

You don't need to send another PR. Commit to this branch only, and squash all the three commits into one. I'll merge it. :)

**Comment by zorroblue** [comment]
Done!

**Comment by OrkoHunter** [comment]
Looks great. In Python, you usually shouldn't exceed 79 characters. That's why I broke the code into pieces.
The standard was introduced in [PEP8](https://www.python.org/dev/peps/pep-0008/).

Can you please `amend` that?

**Comment by zorroblue** [comment]
Now? :)

**Comment by OrkoHunter** [comment]
Cool thanks !

**Comment by zorroblue** [comment]
First real PR merged :D Thanks!

**Pull request merged**
