### PR TITLE
Add command-line completion support for bash and zsh

### LINKED ISSUE #60: [Feature] autocomplete run
Nice and simple tool! Just installed it today. 
My first idea to improve it slightly: suggestions after the run command when pressing tab.
I don't know about the bash stuff, but if it's easy to implement, it would be worth. At least I would probably use it a lot ;)

### PR DESCRIPTION
**Pull request by rahuliyer95**
- Fixes #60 
- Completions available for bash and zsh
- Don't know how to auto-install with pip. Any help here would be appreciated :)

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Hi @rahuliyer95,

Thank you for taking on the feature request. I would also need your help to know how to use change. Could you also please make the following changes? Thanks!

* Add a section in the README (after `Usage` section) on how to use these completion scripts.
* Update [`Usage`](https://github.com/OrkoHunter/keep#usage) section with the new keep command.

**Comment by rahuliyer95** [comment]
I have updated the README to reflect the steps required to enable TAB completion on the command-line. I don't think the newly added completion command will ever be used by anyone as it outputs the stored commands specific to the shell of choice and has no direct use.

**Comment by OrkoHunter** [comment]
Thanks @rahuliyer95 ! Sounds good that it's fine not to document the command. I will get back on this.

**Comment by rahuliyer95** [comment]
Resolved the conflicts and can be merged

**Pull request merged**
